window.MCZ_DETAILS=Object.assign(window.MCZ_DETAILS||{},{
  "1": "Manila is the Philippines' capital by law and is home to Malacañang Palace. Quezon City was the national capital from 1948 to 1976, which makes it an understandable distractor.",
  "2": "Cebu is in Central Visayas. The Visayas is one of the Philippines' three major island groups, alongside Luzon and Mindanao.",
  "3": "The independence declaration against Spanish rule was proclaimed in Kawit, Cavite, on June 12, 1898. The 1946 date refers to later Philippine independence from the United States.",
  "4": "Andrés Bonifacio, a leader of the working-class revolutionaries and co-founder of the Katipunan, became known as the Great Plebeian.",
  "5": "Spain and the United States signed the Treaty of Paris in December 1898 to end the Spanish–American War. It transferred the Philippines to U.S. control.",
  "6": "The Code of Kalantiaw is considered a historical fabrication. Scholar William Henry Scott found no reliable evidence for the claimed early Philippine legal code.",
  "7": "Yoon Se-ri is a South Korean businesswoman. Her accidental landing in North Korea creates the cross-border romance at the center of Crash Landing on You.",
  "8": "Woo Young-woo is a lawyer, and the series follows her work handling legal cases at the fictional law firm Hanbada.",
  "9": "Namkoong Min portrays detective Do Jung-woo in the thriller Awaken, which connects mysterious deaths to the White Night Village.",
  "10": "Rainbow Taxi is the fictional taxi company that secretly provides vigilante-style help to victims in the K-drama Taxi Driver.",
  "11": "Park Chan-wook directed Oldboy (2003). It forms part of his thematic Vengeance Trilogy with Sympathy for Mr. Vengeance and Lady Vengeance.",
  "12": "Prosecutor Hwang Si-mok is the central investigator in Stranger (Secret Forest), where his investigations expose corruption in law and politics.",
  "13": "The pyramids at Giza were built as royal tombs by ancient Egyptians during the Old Kingdom, including the Fourth Dynasty.",
  "14": "Neil Armstrong was first to step onto the lunar surface in July 1969 during Apollo 11; Buzz Aldrin joined him shortly afterward.",
  "15": "The Berlin Wall's border crossings opened on November 9, 1989, after East German authorities announced eased travel rules, marking a key Cold War turning point.",
  "16": "Qin Shi Huang unified warring states in 221 BCE and became China's first emperor under the Qin dynasty.",
  "17": "The Peace of Westphalia, a group of treaties signed in 1648, ended the Thirty Years' War and changed the map of European politics.",
  "18": "Mansa Musa ruled the Mali Empire in West Africa. His famously lavish pilgrimage to Mecca helped spread awareness of Mali's wealth.",
  "19": "The United Nations was formed after World War II to create a forum for international cooperation and reduce the risk of another devastating world war.",
  "20": "Japan uses the yen. The country adopted it as part of modern monetary reforms in the nineteenth century.",
  "21": "The UN's main headquarters sits in New York City, although significant UN offices also operate in Geneva, Vienna, and Nairobi.",
  "22": "Nigeria has Africa's largest population. Its population size and linguistic diversity help distinguish it from other major African countries.",
  "23": "The International Court of Justice is the UN's principal judicial organ. It resolves cases between states that accept its jurisdiction.",
  "24": "South Sudan became independent in July 2011 and joined the United Nations later that month as its newest member state.",
  "25": "The Pacific is Earth's largest ocean basin, covering more surface area than all the world's land put together.",
  "26": "Lunar gravity causes most tidal variation, with solar gravity also playing a part. Their relative alignment produces spring and neap tides.",
  "27": "Wellington is New Zealand's capital near the southern end of the North Island. Auckland has more people, but it is not the capital.",
  "28": "The Andes run along the western side of South America through countries including Chile, Peru, and Argentina.",
  "29": "The Sunda Strait lies between the Indonesian islands of Sumatra and Java, close to the Krakatau volcanic complex.",
  "30": "Transylvania is a historical region of central Romania, surrounded by much of the Carpathian mountain system.",
  "31": "Mars looks red because iron-bearing minerals in its surface dust have oxidized, much like rust on Earth.",
  "32": "Plants absorb carbon dioxide from the air and combine it with water and light energy during photosynthesis to produce sugars, releasing oxygen.",
  "33": "Potassium is K on the periodic table because its symbol derives from the Latinized name kalium, not the English word potassium.",
  "34": "The ampere (A) is the SI unit of electric current, measuring the flow rate of electrical charge. Volts measure potential difference.",
  "35": "Mitochondria carry out most aerobic ATP production in human cells through the electron transport chain and oxidative phosphorylation.",
  "36": "The speed of light in a vacuum is exactly 299,792,458 metres per second, normally rounded to about 300,000 kilometres per second.",
  "37": "Storyboards show the planned camera shots in sequence, helping filmmakers arrange action, framing, and transitions before shooting.",
  "38": "Woody is the cowboy doll in Toy Story, recognizable by his hat, vest, and pull-string voice box. Buzz Lightyear is the space-ranger toy.",
  "39": "James Cameron directed Titanic (1997), combining the historical ocean liner disaster with the fictional story of Jack and Rose.",
  "40": "Wakanda is the fictional African nation in Black Panther. Its technology is fueled by vibranium, a Marvel-universe metal.",
  "41": "Shrek won the very first Academy Award for Best Animated Feature at the 74th Oscars for films released in 2001.",
  "42": "Ennio Morricone wrote the iconic whistling main theme and soundtrack for The Good, the Bad and the Ugly.",
  "43": "A standard violin has four strings, tuned G, D, A, and E from lowest to highest. Five-string violins are variations, not standard.",
  "44": "A time signature such as 4/4 specifies the number of beats in each measure and which note value counts as one beat.",
  "45": "Dancing Queen is a song by the Swedish pop group ABBA, originally released in 1976.",
  "46": "Crescendo tells performers to gradually increase volume. Its opposite, diminuendo or decrescendo, means gradually softer.",
  "47": "Igor Stravinsky composed the ballet The Rite of Spring, which caused a notorious uproar at its 1913 Paris premiere.",
  "48": "A minor and C major have the same key signature—no sharps or flats—so A minor is the relative minor of C major.",
  "49": "Standard basketball is five-on-five: five players per team compete on court, while additional players can substitute.",
  "50": "The feathered or synthetic skirt of a shuttlecock produces heavy aerodynamic drag, making it decelerate rapidly after a smash.",
  "51": "An Olympic long-course swimming pool is 50 metres long. Short-course pools are usually 25 metres.",
  "52": "An American football touchdown is worth six points by itself, with an additional conversion attempt available afterward.",
  "53": "At 40–40 in tennis, the score is called deuce. A player usually must then win two consecutive points to win the game.",
  "54": "Athens in Greece hosted the first modern Olympics in 1896, a revival inspired by the ancient Olympic tradition.",
  "55": "USB stands for Universal Serial Bus, a common standard for connecting peripherals and transferring power or data.",
  "56": "Two-factor authentication requires evidence beyond the password—such as a security key or app code—so a stolen password alone is less useful.",
  "57": "HTML means HyperText Markup Language and describes the structure and content of webpages; CSS styles their appearance.",
  "58": "CSS stands for Cascading Style Sheets. It controls presentation such as typography, colors, spacing, and page layout.",
  "59": "DNS translates human-readable domain names into network addresses such as IP addresses so computers can find the right server.",
  "60": "Merge sort divides a collection into smaller pieces and merges them back in sorted order, giving average O(n log n) performance.",
  "61": "Yeast ferments sugars and releases carbon dioxide. Those gas bubbles get trapped in gluten-rich dough, causing it to expand.",
  "62": "Sushi traditionally uses specially prepared rice seasoned with vinegar; barley, oats, and quinoa are not the standard base.",
  "63": "Éclairs are made from choux pastry. Moisture in the dough turns to steam in the oven, puffing the pastry into a hollow shell.",
  "64": "Lactic acid bacteria ferment the vegetables and sugars in kimchi, producing acids that create its characteristic tangy flavor.",
  "65": "The Maillard reaction occurs when amino compounds react with reducing sugars during heating, producing complex browning flavors.",
  "66": "Hollandaise emulsifies warm clarified butter with egg yolks. Béchamel instead uses milk thickened by flour and butter.",
  "67": "Bats are the only mammals capable of sustained powered flight; flying squirrels and sugar gliders glide rather than flap to fly.",
  "68": "Many bats emit ultrasonic sounds and listen for echoes that bounce off objects, letting them locate insects in darkness.",
  "69": "A social group of lions is called a pride, often formed around related females and their cubs.",
  "70": "An axolotl is a salamander and therefore an amphibian, even though it retains gills and other juvenile aquatic features as an adult.",
  "71": "Regeneration allows some lizards to replace lost tails; the new tail usually differs from the original in structure.",
  "72": "Whales and dolphins are cetaceans—marine mammals classified within the even-toed ungulate evolutionary lineage.",
  "73": "The Sun is our solar system's central star. Its gravity holds the planets in orbit, and it contains nearly all the system's mass.",
  "74": "Saturn's rings are made mainly of countless chunks of ice and debris. All four giant planets have rings, but Saturn's are by far the most prominent.",
  "75": "Earth lies in the Milky Way, a barred spiral galaxy containing hundreds of billions of stars.",
  "76": "Jupiter hosts the Great Red Spot, a persistent giant storm swirling in the planet's atmosphere.",
  "77": "A Type Ia supernova can occur when a white dwarf in a binary system undergoes a thermonuclear explosion.",
  "78": "The event horizon surrounds a black hole and marks the boundary beyond which outward escape is impossible even for light.",
  "79": "William Shakespeare wrote the tragedy Romeo and Juliet, set around two feuding families in Verona.",
  "80": "J. K. Rowling wrote the Harry Potter novels, beginning with Harry Potter and the Philosopher's Stone in 1997.",
  "81": "“Call me Ishmael” is the memorable first line of Herman Melville's Moby-Dick, introducing its narrator.",
  "82": "Jane Austen wrote Pride and Prejudice, the 1813 novel about Elizabeth Bennet, Mr. Darcy, and social expectations.",
  "83": "Colombian author Gabriel García Márquez wrote One Hundred Years of Solitude, a landmark of magical realism.",
  "84": "George Orwell's Animal Farm takes place on an English farm. The animals' rebellion serves as an allegory of political power."
});