window.MCZ_DETAILS=Object.assign(window.MCZ_DETAILS||{},{
  "1": "Manila is the Philippines' capital by law and is home to Malacañang Palace. Quezon City was the national capital from 1948 to 1976, which makes it an understandable distractor.",
  "2": "Cebu is in Central Visayas. The Visayas is one of the Philippines' three major island groups, alongside Luzon and Mindanao.",
  "3": "The independence declaration against Spanish rule was proclaimed in Kawit, Cavite, on June 12, 1898. The 1946 date refers to later Philippine independence from the United States.",
  "4": "Andrés Bonifacio, a leader of the working-class revolutionaries and co-founder of the Katipunan, became known as the Great Plebeian.",
  "5": "Spain and the United States signed the Treaty of Paris in December 1898 to end the Spanish–American War. It transferred the Philippines to U.S. control.",
  "6": "The Code of Kalantiaw is considered a historical fabrication. Scholar William Henry Scott found no reliable evidence for the claimed early Philippine legal code.",
  "7": "Yoon Se-ri is a South Korean businesswoman. Her accidental landing in North Korea creates the cross-border romance at the center of Crash Landing on You.",
  "8": "Woo Young-woo is a lawyer, and the series follows her work handling legal cases at the fictional law firm Hanbada.",
  "9": "Namkoong Min portrays detective Do Jung-woo in the thriller Awaken, which connects mysterious deaths to the White Night Village.",
  "10": "Rainbow Taxi is the fictional taxi company that secretly provides vigilante-style help to victims in the K-drama Taxi Driver.",
  "11": "Park Chan-wook directed Oldboy (2003). It forms part of his thematic Vengeance Trilogy with Sympathy for Mr. Vengeance and Lady Vengeance.",
  "12": "Prosecutor Hwang Si-mok is the central investigator in Stranger (Secret Forest), where his investigations expose corruption in law and politics.",
  "13": "The pyramids at Giza were built as royal tombs by ancient Egyptians during the Old Kingdom, including the Fourth Dynasty.",
  "14": "Neil Armstrong was first to step onto the lunar surface in July 1969 during Apollo 11; Buzz Aldrin joined him shortly afterward.",
  "15": "The Berlin Wall's border crossings opened on November 9, 1989, after East German authorities announced eased travel rules, marking a key Cold War turning point.",
  "16": "Qin Shi Huang unified warring states in 221 BCE and became China's first emperor under the Qin dynasty.",
  "17": "The Peace of Westphalia, a group of treaties signed in 1648, ended the Thirty Years' War and changed the map of European politics.",
  "18": "Mansa Musa ruled the Mali Empire in West Africa. His famously lavish pilgrimage to Mecca helped spread awareness of Mali's wealth.",
  "19": "The United Nations was formed after World War II to create a forum for international cooperation and reduce the risk of another devastating world war.",
  "20": "Japan uses the yen. The country adopted it as part of modern monetary reforms in the nineteenth century.",
  "21": "The UN's main headquarters sits in New York City, although significant UN offices also operate in Geneva, Vienna, and Nairobi.",
  "22": "Nigeria has Africa's largest population. Its population size and linguistic diversity help distinguish it from other major African countries.",
  "23": "The International Court of Justice is the UN's principal judicial organ. It resolves cases between states that accept its jurisdiction.",
  "24": "South Sudan became independent in July 2011 and joined the United Nations later that month as its newest member state.",
  "25": "The Pacific is Earth's largest ocean basin, covering more surface area than all the world's land put together.",
  "26": "Lunar gravity causes most tidal variation, with solar gravity also playing a part. Their relative alignment produces spring and neap tides.",
  "27": "Wellington is New Zealand's capital near the southern end of the North Island. Auckland has more people, but it is not the capital.",
  "28": "The Andes run along the western side of South America through countries including Chile, Peru, and Argentina.",
  "29": "The Sunda Strait lies between the Indonesian islands of Sumatra and Java, close to the Krakatau volcanic complex.",
  "30": "Transylvania is a historical region of central Romania, surrounded by much of the Carpathian mountain system.",
  "31": "Mars looks red because iron-bearing minerals in its surface dust have oxidized, much like rust on Earth.",
  "32": "Plants absorb carbon dioxide from the air and combine it with water and light energy during photosynthesis to produce sugars, releasing oxygen.",
  "33": "Potassium is K on the periodic table because its symbol derives from the Latinized name kalium, not the English word potassium.",
  "34": "The ampere (A) is the SI unit of electric current, measuring the flow rate of electrical charge. Volts measure potential difference.",
  "35": "Mitochondria carry out most aerobic ATP production in human cells through the electron transport chain and oxidative phosphorylation.",
  "36": "The speed of light in a vacuum is exactly 299,792,458 metres per second, normally rounded to about 300,000 kilometres per second.",
  "37": "Storyboards show the planned camera shots in sequence, helping filmmakers arrange action, framing, and transitions before shooting.",
  "38": "Woody is the cowboy doll in Toy Story, recognizable by his hat, vest, and pull-string voice box. Buzz Lightyear is the space-ranger toy.",
  "39": "James Cameron directed Titanic (1997), combining the historical ocean liner disaster with the fictional story of Jack and Rose.",
  "40": "Wakanda is the fictional African nation in Black Panther. Its technology is fueled by vibranium, a Marvel-universe metal.",
  "41": "Shrek won the very first Academy Award for Best Animated Feature at the 74th Oscars for films released in 2001.",
  "42": "Ennio Morricone wrote the iconic whistling main theme and soundtrack for The Good, the Bad and the Ugly.",
  "43": "A standard violin has four strings, tuned G, D, A, and E from lowest to highest. Five-string violins are variations, not standard.",
  "44": "A time signature such as 4/4 specifies the number of beats in each measure and which note value counts as one beat.",
  "45": "Dancing Queen is a song by the Swedish pop group ABBA, originally released in 1976.",
  "46": "Crescendo tells performers to gradually increase volume. Its opposite, diminuendo or decrescendo, means gradually softer.",
  "47": "Igor Stravinsky composed the ballet The Rite of Spring, which caused a notorious uproar at its 1913 Paris premiere.",
  "48": "A minor and C major have the same key signature—no sharps or flats—so A minor is the relative minor of C major.",
  "49": "Standard basketball is five-on-five: five players per team compete on court, while additional players can substitute.",
  "50": "The feathered or synthetic skirt of a shuttlecock produces heavy aerodynamic drag, making it decelerate rapidly after a smash.",
  "51": "An Olympic long-course swimming pool is 50 metres long. Short-course pools are usually 25 metres.",
  "52": "An American football touchdown is worth six points by itself, with an additional conversion attempt available afterward.",
  "53": "At 40–40 in tennis, the score is called deuce. A player usually must then win two consecutive points to win the game.",
  "54": "Athens in Greece hosted the first modern Olympics in 1896, a revival inspired by the ancient Olympic tradition.",
  "55": "USB stands for Universal Serial Bus, a common standard for connecting peripherals and transferring power or data.",
  "56": "Two-factor authentication requires evidence beyond the password—such as a security key or app code—so a stolen password alone is less useful.",
  "57": "HTML means HyperText Markup Language and describes the structure and content of webpages; CSS styles their appearance.",
  "58": "CSS stands for Cascading Style Sheets. It controls presentation such as typography, colors, spacing, and page layout.",
  "59": "DNS translates human-readable domain names into network addresses such as IP addresses so computers can find the right server.",
  "60": "Merge sort divides a collection into smaller pieces and merges them back in sorted order, giving average O(n log n) performance.",
  "61": "Yeast ferments sugars and releases carbon dioxide. Those gas bubbles get trapped in gluten-rich dough, causing it to expand.",
  "62": "Sushi traditionally uses specially prepared rice seasoned with vinegar; barley, oats, and quinoa are not the standard base.",
  "63": "Éclairs are made from choux pastry. Moisture in the dough turns to steam in the oven, puffing the pastry into a hollow shell.",
  "64": "Lactic acid bacteria ferment the vegetables and sugars in kimchi, producing acids that create its characteristic tangy flavor.",
  "65": "The Maillard reaction occurs when amino compounds react with reducing sugars during heating, producing complex browning flavors.",
  "66": "Hollandaise emulsifies warm clarified butter with egg yolks. Béchamel instead uses milk thickened by flour and butter.",
  "67": "Bats are the only mammals capable of sustained powered flight; flying squirrels and sugar gliders glide rather than flap to fly.",
  "68": "Many bats emit ultrasonic sounds and listen for echoes that bounce off objects, letting them locate insects in darkness.",
  "69": "A social group of lions is called a pride, often formed around related females and their cubs.",
  "70": "An axolotl is a salamander and therefore an amphibian, even though it retains gills and other juvenile aquatic features as an adult.",
  "71": "Regeneration allows some lizards to replace lost tails; the new tail usually differs from the original in structure.",
  "72": "Whales and dolphins are cetaceans—marine mammals classified within the even-toed ungulate evolutionary lineage.",
  "73": "The Sun is our solar system's central star. Its gravity holds the planets in orbit, and it contains nearly all the system's mass.",
  "74": "Saturn's rings are made mainly of countless chunks of ice and debris. All four giant planets have rings, but Saturn's are by far the most prominent.",
  "75": "Earth lies in the Milky Way, a barred spiral galaxy containing hundreds of billions of stars.",
  "76": "Jupiter hosts the Great Red Spot, a persistent giant storm swirling in the planet's atmosphere.",
  "77": "A Type Ia supernova can occur when a white dwarf in a binary system undergoes a thermonuclear explosion.",
  "78": "The event horizon surrounds a black hole and marks the boundary beyond which outward escape is impossible even for light.",
  "79": "William Shakespeare wrote the tragedy Romeo and Juliet, set around two feuding families in Verona.",
  "80": "J. K. Rowling wrote the Harry Potter novels, beginning with Harry Potter and the Philosopher's Stone in 1997.",
  "81": "“Call me Ishmael” is the memorable first line of Herman Melville's Moby-Dick, introducing its narrator.",
  "82": "Jane Austen wrote Pride and Prejudice, the 1813 novel about Elizabeth Bennet, Mr. Darcy, and social expectations.",
  "83": "Colombian author Gabriel García Márquez wrote One Hundred Years of Solitude, a landmark of magical realism.",
  "84": "George Orwell's Animal Farm takes place on an English farm. The animals' rebellion serves as an allegory of political power."
});
window.MCZ_DETAILS=Object.assign(window.MCZ_DETAILS||{},{
  "85": "Leonardo da Vinci painted the Mona Lisa in the Renaissance. The portrait is famous for its subtle sfumato shading and is displayed at the Louvre.",
  "86": "Mixing traditional blue and yellow paints usually creates green because the pigments absorb and reflect different wavelengths of light.",
  "87": "Vincent van Gogh painted The Starry Night in 1889 while living at an asylum in Saint-Rémy-de-Provence.",
  "88": "Claude Monet is strongly associated with Impressionism; the movement took its name from his painting Impression, Sunrise.",
  "89": "Auguste Rodin created The Thinker, originally conceived as a figure for his larger sculptural project The Gates of Hell.",
  "90": "Egg tempera mixes pigment with egg yolk as a binder. It was frequently used in European painting before oil paint became widespread.",
  "91": "Poseidon is the Greek god of the sea, storms, and earthquakes, commonly shown carrying a trident.",
  "92": "Thor is the Norse god of thunder. His hammer Mjölnir is one of his best-known attributes.",
  "93": "Athena represents wisdom, strategy, and crafts in Greek mythology; the city of Athens regarded her as its patron deity.",
  "94": "Icarus ignored his father's warning and flew too high with wax-bound wings. Heat softened the wax and he fell into the sea.",
  "95": "Yggdrasil is the immense world tree in Norse mythology that connects multiple realms in the cosmos.",
  "96": "Charon is the boatman who ferries the dead across a river of the underworld in Greek myth, often for a coin.",
  "97": "CEO means Chief Executive Officer. This executive generally leads overall management and organizational strategy.",
  "98": "Revenue is income generated from sales before business expenses are deducted. Profit is what's left after applicable costs.",
  "99": "ROI stands for Return on Investment, relating an investment's gain or loss to its cost.",
  "100": "A balance sheet reports assets, liabilities, and owners' equity at a particular date, so it is a snapshot rather than a period's profit.",
  "101": "Variable costs change with output level. Raw materials, for example, usually cost more as additional units are produced.",
  "102": "Current ratio = current assets divided by current liabilities, indicating the ability to cover short-term debts using short-term resources.",
  "103": "A monitor is the output device that displays computer-generated visual information. A CPU processes instructions rather than displaying pictures by itself.",
  "104": "CPU means Central Processing Unit, which executes program instructions and coordinates computing tasks.",
  "105": "RAM is ordinarily volatile: it needs electrical power to retain the data currently held in memory.",
  "106": "In modern computer systems, a byte conventionally consists of eight bits, each a binary zero or one.",
  "107": "A cryptographic hash maps data to a fixed-size digest and is designed to make reverse reconstruction and collisions difficult.",
  "108": "TLS, or Transport Layer Security, protects HTTPS connections by encrypting transmitted data and helping authenticate the server.",
  "109": "Bees gather nectar from flowers as an energy source, while pollen supplies proteins and other nutrients.",
  "110": "Roots absorb much of a tree's water through soil contact. Tiny root hairs greatly increase the area available for uptake.",
  "111": "Evaporation occurs when molecules escape from liquid water into vapor, even when the water is cooler than its boiling point.",
  "112": "Tundra has a cold climate, little tree growth, and in many areas permafrost—ground that remains frozen for at least two years.",
  "113": "An endemic species occurs naturally only in a particular geographic region, so local habitat loss can threaten its entire population.",
  "114": "Nitrogen-fixing microbes convert atmospheric nitrogen into ammonia or related usable nitrogen compounds, making nitrogen available to ecosystems.",
  "115": "Portuguese is Brazil's main official language, reflecting its colonial history under Portugal rather than Spain.",
  "116": "Modern is a common antonym of ancient: the words contrast newer or present-day periods with very old ones.",
  "117": "Meticulous means extremely careful about details, so thorough is the closest synonym among the choices.",
  "118": "Homographs have the same written spelling but different meanings. Some also differ in pronunciation, as with lead.",
  "119": "A metaphor states that one thing is another; a simile more explicitly uses comparison words such as like or as.",
  "120": "Etymology studies how words originated, changed meanings, and developed across languages and historical periods.",
  "121": "Creepers are hostile mobs in Minecraft, famous for approaching quietly and exploding near the player.",
  "122": "A chess knight moves two squares in one direction and one at a right angle, making an L shape; it may jump over other pieces.",
  "123": "A standard Tetris shape is a tetromino, composed of four square blocks connected edge to edge.",
  "124": "Nintendo released the Switch hybrid game console in 2017, combining handheld and television play.",
  "125": "En passant permits a pawn to capture an opposing pawn that has just advanced two squares as though it had moved one, but only immediately afterward.",
  "126": "The Tetris O-piece is a square. Its appearance has fourfold rotational symmetry, so every quarter-turn looks identical.",
  "127": "Ferdinand Marcos proclaimed the 1973 Philippine Constitution ratified during martial law; the manner of ratification remains historically controversial.",
  "128": "Baybayin is an indigenous script used in parts of the Philippine archipelago before Spanish colonization and early in the colonial period.",
  "129": "Kim Eun-hee wrote the television series Signal (2016), known for its detectives communicating across different years.",
  "130": "Mr. Sunshine is set in the final decades of the Joseon era, when foreign powers and domestic factions competed for influence over Korea.",
  "131": "The Peace of Westphalia consists of 1648 treaties negotiated at Münster and Osnabrück, conventionally cited as ending the Thirty Years' War.",
  "132": "Justinian I was emperor of the Eastern Roman (Byzantine) Empire in the sixth century and sponsored the Corpus Juris Civilis.",
  "133": "The International Court of Justice hears disputes between consenting states and gives advisory opinions on international law; the ICC instead prosecutes individuals.",
  "134": "The Treaty of Rome was signed in 1957 and created the European Economic Community, a predecessor of today's European Union.",
  "135": "The Sunda Strait is the waterway between Sumatra and Java in Indonesia; the Krakatau volcanic island group lies in it.",
  "136": "The Mariana Trench contains Challenger Deep, the deepest known point in the world's oceans.",
  "137": "The second law of thermodynamics says the entropy of an isolated system does not decrease during a spontaneous process.",
  "138": "Mitochondria contain their own DNA and are the main site of oxidative phosphorylation, the energy-producing final stage of aerobic respiration.",
  "139": "Akira Kurosawa directed Seven Samurai (1954), which helped inspire the later Magnificent Seven and many ensemble adventure films.",
  "140": "Loving Vincent is animated using individually painted oil-paint frames inspired by Vincent van Gogh's distinctive style.",
  "141": "Mozart composed The Magic Flute, a German-language opera that premiered in Vienna in 1791.",
  "142": "A tritone spans six semitones, splitting the twelve-semitone octave into two equal halves.",
  "143": "In snooker, potting the black ball earns seven points—more than any other colored ball.",
  "144": "In épée fencing, the entire body is a valid target; foil and sabre restrict the target area.",
  "145": "RSA takes its name from its inventors Ronald Rivest, Adi Shamir, and Leonard Adleman. It is a well-known public-key cryptosystem.",
  "146": "NFC stands for Near Field Communication, used at short ranges for contactless cards, taps, and device pairing.",
  "147": "The Maillard reaction creates browning, aromas, and flavors when sugars react with amino-containing compounds during heating.",
  "148": "Gluten is the elastic protein network formed when flour proteins gliadin and glutenin are hydrated and worked together.",
  "149": "Whales and dolphins are cetaceans, aquatic mammals that evolved from land-dwelling hoofed ancestors.",
  "150": "Hemocyanin uses copper to bind oxygen in the blood or hemolymph of many mollusks and arthropods, sometimes making it blue when oxygenated.",
  "151": "Titan, Saturn's largest moon, has a thick nitrogen-rich atmosphere and lakes of liquid methane and ethane.",
  "152": "A black hole's event horizon is its boundary of no return: once crossed, even light cannot escape to the outside universe.",
  "153": "Mikhail Bulgakov wrote The Master and Margarita, a Russian novel published posthumously after his death.",
  "154": "In medias res is a Latin phrase meaning into the middle of things; it describes a story beginning after its main action has already started.",
  "155": "Hieronymus Bosch painted The Garden of Earthly Delights, a fantastical triptych currently in Madrid's Prado Museum.",
  "156": "Georges Braque and Pablo Picasso helped pioneer Cubism by breaking scenes into overlapping geometric viewpoints.",
  "157": "Heimdall is the Norse divine watchman who guards the Bifröst rainbow bridge linking realms.",
  "158": "Hestia is the Greek goddess of the hearth and home, associated with the sacred fire at the heart of a household.",
  "159": "The current ratio divides current assets by current liabilities to estimate a firm's short-term liquidity.",
  "160": "The critical path is the longest sequence of dependent activities controlling a project's minimum completion time. Delays on it typically affect the finish date.",
  "161": "A queue follows first in, first out: items are removed in their arrival order, unlike a stack's last-in, first-out behavior.",
  "162": "The SQL HAVING clause filters groups after aggregation, whereas WHERE filters individual rows before grouping.",
  "163": "Parasitism benefits the parasite while harming its host; the parasite depends on the host for resources.",
  "164": "The tropopause separates the weather-bearing troposphere from the stratosphere; its altitude varies with geography and weather.",
  "165": "A morpheme is the smallest meaningful language unit, such as a whole word or a meaningful prefix like un-.",
  "166": "A lingua franca is a shared language used by people with different native tongues, enabling communication across groups.",
  "167": "Alexey Pajitnov created Tetris in 1984 while working at a Soviet computer center in Moscow.",
  "168": "The # symbol denotes checkmate in modern algebraic chess notation; + denotes a check that has not necessarily ended the game."
});