// Shared Mind Clash Z question bank. Arcade prototype source.
export const RAW=[
['Philippines','easy','What is the capital of the Philippines?',['Manila','Cebu City','Davao City','Quezon City'],0,'Manila has been the national capital since the Spanish colonial era.'],
['Philippines','easy','Which island group includes Cebu?',['Visayas','Luzon','Mindanao','Palawan'],0,'Cebu is in the Central Visayas region.'],
['Philippines','medium','When was Philippine independence from Spain declared?',['1898','1901','1946','1986'],0,'The declaration was made in Kawit, Cavite, on June 12, 1898.'],
['Philippines','medium','Who was known as the “Great Plebeian”?',['Manuel Quezon','Andrés Bonifacio','Ramon Magsaysay','Emilio Aguinaldo'],1,'Bonifacio co-founded the Katipunan, which challenged Spanish rule.'],
['Philippines','hard','Which treaty ended the Spanish-American War?',['Treaty of Paris','Treaty of Manila','Treaty of Tordesillas','Treaty of Washington'],0,'The 1898 Treaty of Paris transferred control of the Philippines from Spain to the United States.'],
['Philippines','hard','Historians generally consider the Code of Kalantiaw to be what?',['A fabrication','A Spanish decree','A confirmed medieval law','A U.S. statute'],0,'Historian William Henry Scott helped demonstrate that the supposed code lacked credible historical evidence.'],
['K-Drama','easy','Where is Yoon Se-ri from in Crash Landing on You?',['South Korea','North Korea','Japan','China'],0,'The romance follows a South Korean businesswoman who unexpectedly lands in North Korea.'],
['K-Drama','easy','What is Woo Young-woo’s profession?',['Lawyer','Doctor','Detective','Teacher'],0,'Extraordinary Attorney Woo premiered in 2022.'],
['K-Drama','medium','Who played Do Jung-woo in Awaken (2020)?',['Namkoong Min','Lee Je-hoon','Ji Sung','Kim Nam-gil'],0,'Awaken combines criminal investigation with a mystery linked to the White Night Village.'],
['K-Drama','medium','What is the revenge taxi company called in Taxi Driver?',['Rainbow Taxi','Black Taxi','Golden Cab','Bluebird Taxi'],0,'The company carries out secret missions for people seeking justice.'],
['K-Drama','hard','Who directed the South Korean film Oldboy (2003)?',['Park Chan-wook','Bong Joon-ho','Kim Jee-woon','Hong Sang-soo'],0,'Oldboy is the middle installment in Park Chan-wook’s Vengeance Trilogy.'],
['K-Drama','hard','Which drama features prosecutor Hwang Si-mok?',['Stranger','Signal','Beyond Evil','Mouse'],0,'Stranger, also known as Secret Forest, stars Cho Seung-woo.'],
['History','easy','Which civilization built the pyramids at Giza?',['Ancient Egyptians','Ancient Romans','Aztecs','Persians'],0,'The Great Pyramid was built during the Fourth Dynasty.'],
['History','easy','Who first walked on the Moon?',['Neil Armstrong','Buzz Aldrin','Yuri Gagarin','John Glenn'],0,'Apollo 11 landed on the Moon in July 1969.'],
['History','medium','In what year did the Berlin Wall fall?',['1989','1985','1991','1979'],0,'The opening of Berlin Wall checkpoints became a symbol of the Cold War’s end.'],
['History','medium','Who first unified China as emperor?',['Qin Shi Huang','Kublai Khan','Sun Yat-sen','Wu Zetian'],0,'The Qin dynasty began the imperial era in 221 BCE.'],
['History','hard','Which 1648 settlement ended the Thirty Years’ War?',['Peace of Westphalia','Treaty of Utrecht','Congress of Vienna','Treaty of Versailles'],0,'The treaties helped reshape the political order of Europe.'],
['History','hard','Mansa Musa ruled which empire?',['Mali Empire','Songhai Empire','Ghana Empire','Benin Empire'],0,'His pilgrimage to Mecca became famous for its display of wealth.'],
['World','easy','What does UN stand for?',['United Nations','United Network','Universal Nation','Union of Neighbors'],0,'The UN was founded in 1945.'],
['World','easy','What is the currency of Japan?',['Yen','Won','Yuan','Baht'],0,'The yen has been Japan’s official currency since the nineteenth century.'],
['World','medium','Where is the UN headquarters?',['New York City','Geneva','Paris','Vienna'],0,'The UN also maintains major offices in Geneva, Vienna and Nairobi.'],
['World','medium','Which country has the largest population in Africa?',['Nigeria','Egypt','South Africa','Kenya'],0,'Nigeria is in West Africa and is home to hundreds of languages.'],
['World','hard','What is the principal judicial organ of the UN?',['International Court of Justice','International Criminal Court','World Trade Organization','Permanent Court of Arbitration'],0,'The International Court of Justice sits in The Hague.'],
['World','hard','Which country joined the UN in 2011?',['South Sudan','Montenegro','Timor-Leste','Eritrea'],0,'South Sudan became independent in 2011.'],
['Geography','easy','What is Earth’s largest ocean?',['Pacific Ocean','Atlantic Ocean','Indian Ocean','Arctic Ocean'],0,'The Pacific covers more area than all Earth’s land combined.'],
['Geography','easy','Which continent contains the Sahara?',['Africa','Asia','South America','Australia'],0,'The Sahara stretches across North Africa.'],
['Geography','medium','What is the capital of New Zealand?',['Wellington','Auckland','Christchurch','Hamilton'],0,'Wellington sits near the southern tip of the North Island.'],
['Geography','medium','The Andes lie along which continent?',['South America','Asia','Africa','Europe'],0,'The Andes run through several South American countries.'],
['Geography','hard','Which strait separates Sumatra and Java?',['Sunda Strait','Malacca Strait','Luzon Strait','Bering Strait'],0,'The Sunda Strait is close to the volcanic island Anak Krakatau.'],
['Geography','hard','Which country contains Transylvania?',['Romania','Hungary','Bulgaria','Serbia'],0,'Transylvania is a historical region in central Romania.'],
['Science','easy','Which planet is the Red Planet?',['Mars','Venus','Jupiter','Mercury'],0,'Iron oxide dust contributes to the red appearance of Mars.'],
['Science','easy','What gas do plants take in during photosynthesis?',['Carbon dioxide','Oxygen','Nitrogen','Helium'],0,'Photosynthesis uses light energy to produce sugars.'],
['Science','medium','What is the chemical symbol for potassium?',['K','P','Pt','Po'],0,'K comes from the Latin name kalium.'],
['Science','medium','What is the SI unit of electric current?',['Ampere','Volt','Watt','Ohm'],0,'An ampere measures the rate of electric charge flow.'],
['Science','hard','What organelle performs most aerobic respiration in human cells?',['Mitochondrion','Ribosome','Golgi apparatus','Nucleus'],0,'Mitochondria help generate ATP through oxidative phosphorylation.'],
['Science','hard','Approximately how fast does light travel in vacuum?',['300,000 km/s','30,000 km/s','3,000 km/s','3,000,000 km/s'],0,'The defined value is exactly 299,792,458 metres per second.'],
['Movies','easy','What color are the Minions?',['Yellow','Blue','Pink','Green'],0,'The Minions appeared in Despicable Me in 2010.'],
['Movies','easy','Who is the cowboy toy in Toy Story?',['Woody','Buzz','Rex','Slinky'],0,'Woody is voiced by Tom Hanks in the English-language films.'],
['Movies','medium','Who directed Titanic (1997)?',['James Cameron','Steven Spielberg','Peter Jackson','Ridley Scott'],0,'Titanic won 11 Academy Awards.'],
['Movies','medium','What is the fictional African country in Black Panther?',['Wakanda','Genosha','Latveria','Zamunda'],0,'Wakanda is home to the fictional metal vibranium.'],
['Movies','hard','Which film won the first Academy Award for Best Animated Feature?',['Shrek','Spirited Away','Finding Nemo','The Incredibles'],0,'The award category debuted at the 74th Academy Awards.'],
['Movies','hard','Who composed the score for The Good, the Bad and the Ugly?',['Ennio Morricone','John Williams','Hans Zimmer','Bernard Herrmann'],0,'Its main theme became one of the most recognizable Western film scores.'],
['Music','easy','How many strings does a standard violin have?',['Four','Five','Six','Seven'],0,'Violin strings are normally tuned G, D, A and E.'],
['Music','easy','What instrument has black and white keys?',['Piano','Drum kit','Violin','Trumpet'],0,'Modern full-size pianos typically have 88 keys.'],
['Music','medium','Which group recorded Dancing Queen?',['ABBA','Queen','Bee Gees','Fleetwood Mac'],0,'Dancing Queen was released in the 1970s.'],
['Music','medium','Which term means gradually getting louder?',['Crescendo','Diminuendo','Staccato','Legato'],0,'Crescendo marks a rise in musical dynamics.'],
['Music','hard','Which composer wrote The Rite of Spring?',['Igor Stravinsky','Claude Debussy','Gustav Mahler','Maurice Ravel'],0,'Its 1913 premiere in Paris is famous for the audience uproar.'],
['Music','hard','What is the relative minor of C major?',['A minor','D minor','E minor','G minor'],0,'Relative major and minor keys use the same key signature.'],
['Sports','easy','How many players are on the court for one basketball team?',['Five','Six','Seven','Eleven'],0,'Basketball teams can substitute players during play stoppages.'],
['Sports','easy','What sport uses a shuttlecock?',['Badminton','Tennis','Squash','Table tennis'],0,'Shuttlecocks have a distinctive feathered or synthetic skirt.'],
['Sports','medium','How long is an Olympic swimming pool?',['50 metres','25 metres','75 metres','100 metres'],0,'Short-course competition pools measure 25 metres.'],
['Sports','medium','How many points is a touchdown worth before conversion?',['Six','Five','Seven','Eight'],0,'American football allows extra-point and two-point conversion attempts.'],
['Sports','hard','In tennis, what is the score called at 40–40?',['Deuce','Advantage','Love','Break point'],0,'A game normally requires a two-point margin after deuce.'],
['Sports','hard','Which country hosted the first modern Olympics in 1896?',['Greece','France','United Kingdom','Italy'],0,'The first modern Olympic Games were held in Athens.'],
['Technology','easy','What does USB stand for?',['Universal Serial Bus','Unified Storage Board','User Signal Bridge','Universal System Backup'],0,'USB is used for data connections and power delivery.'],
['Technology','easy','What device is used to move a cursor on a computer?',['Mouse','Router','Modem','Printer'],0,'Early computer mice used mechanical tracking mechanisms.'],
['Technology','medium','What does HTML stand for?',['HyperText Markup Language','High Transfer Machine Language','Hyper Tool Mark Language','Home Text Management Layer'],0,'HTML structures web content; CSS handles much of its presentation.'],
['Technology','medium','Which language is primarily used to style web pages?',['CSS','SQL','Python','Bash'],0,'CSS stands for Cascading Style Sheets.'],
['Technology','hard','What does DNS primarily translate?',['Domain names to IP addresses','Images to text','Passwords to hashes','Files to databases'],0,'DNS lets browsers locate services by human-readable domain names.'],
['Technology','hard','Which sorting algorithm has average O(n log n) time complexity?',['Merge sort','Bubble sort','Insertion sort','Selection sort'],0,'Merge sort recursively divides data and combines sorted pieces.'],
['Food','easy','What is the main ingredient in guacamole?',['Avocado','Cucumber','Spinach','Peas'],0,'Guacamole has roots in Mexican cuisine.'],
['Food','easy','Which grain is typically used for sushi rice?',['Rice','Barley','Quinoa','Oats'],0,'Sushi rice is seasoned with vinegar, sugar and salt.'],
['Food','medium','What pastry is used in a classic éclair?',['Choux pastry','Puff pastry','Filo pastry','Shortcrust pastry'],0,'Choux pastry expands through steam during baking.'],
['Food','medium','What gives traditional kimchi much of its fermented tang?',['Lactic acid bacteria','Baking soda','Distilled vinegar only','Yeast frosting'],0,'Lactic acid fermentation helps preserve the vegetables.'],
['Food','hard','What does the Maillard reaction primarily involve?',['Amino compounds and reducing sugars','Salt and water','Alcohol and oil','Starch and ice'],0,'This series of reactions creates many browned-food flavors.'],
['Food','hard','Which sauce is traditionally emulsified from egg yolks and clarified butter?',['Hollandaise','Béchamel','Velouté','Tomato sauce'],0,'Hollandaise is one of the classic French mother sauces.'],
['Animals','easy','Which mammal can fly under its own power?',['Bat','Flying squirrel','Sugar glider','Colugo'],0,'Bats have wings formed from a membrane supported by long finger bones.'],
['Animals','easy','Which animal is known for black and white stripes?',['Zebra','Giraffe','Moose','Tapir'],0,'Every zebra has a unique stripe pattern.'],
['Animals','medium','What is a group of lions commonly called?',['Pride','Pack','Herd','School'],0,'Lion prides commonly include related females.'],
['Animals','medium','What kind of animal is an axolotl?',['Amphibian','Reptile','Mammal','Fish'],0,'Axolotls are salamanders that retain aquatic juvenile traits as adults.'],
['Animals','hard','What process lets some lizards regrow a lost tail?',['Regeneration','Metamorphosis','Moulting','Budding'],0,'Regrown tails typically differ structurally from original tails.'],
['Animals','hard','Which taxonomic order includes whales and dolphins?',['Cetacea','Primates','Carnivora','Rodentia'],0,'Modern classification places cetaceans within the even-toed ungulate lineage.'],
['Space','easy','What star is at the center of our solar system?',['The Sun','Sirius','Polaris','Betelgeuse'],0,'The Sun contains nearly all the mass of our solar system.'],
['Space','easy','Which planet is famous for its prominent rings?',['Saturn','Venus','Mars','Mercury'],0,'All four giant planets have ring systems, but Saturn’s are especially visible.'],
['Space','medium','What galaxy contains Earth?',['Milky Way','Andromeda','Triangulum','Whirlpool'],0,'The Milky Way is a barred spiral galaxy.'],
['Space','medium','Which planet has the Great Red Spot?',['Jupiter','Uranus','Neptune','Mars'],0,'The Great Red Spot is a long-lived giant storm.'],
['Space','hard','What type of star explosion can result from a white dwarf in a binary system?',['Type Ia supernova','Gamma-ray pulsar','Solar flare','Planetary transit'],0,'Type Ia supernovae have been useful in estimating cosmic distances.'],
['Space','hard','What is the boundary around a black hole beyond which light cannot escape?',['Event horizon','Heliopause','Photosphere','Magnetopause'],0,'The event horizon is a causal boundary, not a solid surface.'],
['Literature','easy','Who wrote Romeo and Juliet?',['William Shakespeare','Charles Dickens','Jane Austen','Mark Twain'],0,'The tragedy was written in the late sixteenth century.'],
['Literature','easy','Who created Harry Potter?',['J. K. Rowling','Suzanne Collins','Rick Riordan','C. S. Lewis'],0,'The first Harry Potter novel was published in 1997.'],
['Literature','medium','Which novel begins with “Call me Ishmael”?',['Moby-Dick','The Great Gatsby','Jane Eyre','Dracula'],0,'Herman Melville published Moby-Dick in 1851.'],
['Literature','medium','Who wrote Pride and Prejudice?',['Jane Austen','Mary Shelley','Emily Brontë','George Eliot'],0,'The novel was first published in 1813.'],
['Literature','hard','Which author wrote One Hundred Years of Solitude?',['Gabriel García Márquez','Mario Vargas Llosa','Jorge Luis Borges','Pablo Neruda'],0,'The novel is closely associated with magical realism.'],
['Literature','hard','What is the fictional setting of George Orwell’s Animal Farm?',['A farm in England','A space station','A desert island','A medieval castle'],0,'The novella uses farm animals to explore political power and corruption.'],
['Art','easy','Who painted the Mona Lisa?',['Leonardo da Vinci','Vincent van Gogh','Pablo Picasso','Claude Monet'],0,'The Mona Lisa is exhibited at the Louvre in Paris.'],
['Art','easy','Which color results from mixing blue and yellow paint?',['Green','Orange','Purple','Pink'],0,'Traditional pigment mixing differs from mixing colored light.'],
['Art','medium','Which artist painted The Starry Night?',['Vincent van Gogh','Edvard Munch','Paul Cézanne','Henri Matisse'],0,'Van Gogh painted it in 1889 while staying in Saint-Rémy.'],
['Art','medium','Which art movement is associated with Claude Monet?',['Impressionism','Cubism','Surrealism','Futurism'],0,'The movement’s name came from Monet’s Impression, Sunrise.'],
['Art','hard','Which artist produced the sculpture The Thinker?',['Auguste Rodin','Donatello','Michelangelo','Bernini'],0,'The Thinker originated as part of Rodin’s The Gates of Hell project.'],
['Art','hard','Which painting technique uses pigments suspended in egg yolk?',['Egg tempera','Fresco','Encaustic','Oil glazing'],0,'Egg tempera was widely used before oil painting became dominant in Europe.'],
['Mythology','easy','Who is the Greek god of the sea?',['Poseidon','Apollo','Ares','Hermes'],0,'Poseidon is often depicted carrying a trident.'],
['Mythology','easy','Which Norse god is associated with thunder?',['Thor','Loki','Odin','Baldr'],0,'Thor’s hammer is called Mjölnir.'],
['Mythology','medium','Who was the Greek goddess of wisdom?',['Athena','Hera','Aphrodite','Demeter'],0,'Athena was a patron deity of Athens.'],
['Mythology','medium','In Greek myth, who flew too close to the Sun?',['Icarus','Perseus','Orpheus','Theseus'],0,'Icarus’s wax-bound wings melted after he ignored a warning.'],
['Mythology','hard','What is the name of the world tree in Norse cosmology?',['Yggdrasil','Bifröst','Jötunheimr','Valhalla'],0,'Yggdrasil connects realms in Norse mythological tradition.'],
['Mythology','hard','Which figure ferries souls across the river in Greek mythology?',['Charon','Cerberus','Hades','Thanatos'],0,'Charon traditionally requires a coin for passage.'],
['Business','easy','What does CEO stand for?',['Chief Executive Officer','Chief Engineering Officer','Corporate Equity Owner','Client Engagement Operator'],0,'A CEO is usually responsible for an organization’s overall management.'],
['Business','easy','What is revenue?',['Money earned from sales','Profit after all expenses','A business loan','A tax refund'],0,'Revenue and profit are different measures.'],
['Business','medium','What does ROI stand for?',['Return on Investment','Rate of Inventory','Revenue over Interest','Record of Income'],0,'ROI relates returns to the cost of an investment.'],
['Business','medium','What is a balance sheet primarily a snapshot of?',['Assets, liabilities and equity','Only annual sales','Only marketing spend','Only staff schedules'],0,'A balance sheet describes a company’s financial position at a point in time.'],
['Business','hard','Which cost changes with production volume in the short run?',['Variable cost','Sunk cost','Fixed cost','Historical cost'],0,'Raw-material spending often varies with production output.'],
['Business','hard','What does a current ratio compare?',['Current assets to current liabilities','Profit to revenue','Cash to share price','Debt to market size'],0,'This ratio is commonly used as a liquidity indicator.'],
['Computers','easy','Which component displays images on a computer screen?',['Monitor','Keyboard','Microphone','Scanner'],0,'Monitors are output devices.'],
['Computers','easy','What does CPU stand for?',['Central Processing Unit','Computer Power Utility','Central Program User','Control Peripheral Unit'],0,'The CPU executes instructions and coordinates many operations.'],
['Computers','medium','Which memory is normally volatile?',['RAM','SSD','DVD','USB flash'],0,'Ordinary RAM loses stored information without power.'],
['Computers','medium','Which data unit is typically eight bits?',['Byte','Nibble','Word','Packet'],0,'A byte conventionally contains eight bits in modern computing.'],
['Computers','hard','What is the purpose of a cryptographic hash function?',['Create a fixed-size digest','Reverse encryption without keys','Increase clock speed','Compress video losslessly'],0,'Secure hashes are designed to make finding collisions computationally difficult.'],
['Computers','hard','Which protocol establishes encrypted web connections in HTTPS?',['TLS','FTP','SMTP','DHCP'],0,'TLS helps authenticate servers and protect data in transit.'],
['Nature','easy','What do bees commonly collect from flowers?',['Nectar','Sand','Salt','Clay'],0,'Bees also collect pollen as a protein source.'],
['Nature','easy','What part of a tree usually absorbs water from soil?',['Roots','Flowers','Bark','Fruit'],0,'Root hairs increase the surface area for absorption.'],
['Nature','medium','What is the process of water changing into vapor?',['Evaporation','Condensation','Precipitation','Freezing'],0,'Evaporation can happen below boiling temperature.'],
['Nature','medium','What biome features permafrost and few trees?',['Tundra','Savanna','Rainforest','Temperate woodland'],0,'Permafrost is ground that remains frozen for at least two consecutive years.'],
['Nature','hard','What term describes species found only in one geographic area?',['Endemic','Invasive','Migratory','Cosmopolitan'],0,'Endemism may make species particularly vulnerable to habitat change.'],
['Nature','hard','What process converts atmospheric nitrogen into biologically useful compounds?',['Nitrogen fixation','Respiration','Transpiration','Denitrification'],0,'Some bacteria can fix nitrogen into ammonia.'],
['Language','easy','Which language is primarily spoken in Brazil?',['Portuguese','Spanish','French','Italian'],0,'Brazil is the world’s largest Portuguese-speaking country.'],
['Language','easy','What is the opposite of “ancient”?',['Modern','Antique','Historic','Aged'],0,'Antonyms are words with opposite meanings.'],
['Language','medium','Which is a synonym for “meticulous”?',['Thorough','Careless','Hasty','Vague'],0,'Meticulous work shows careful attention to detail.'],
['Language','medium','What is a word with the same spelling but different meaning called?',['Homograph','Antonym','Acronym','Suffix'],0,'Homographs can sometimes also have different pronunciations.'],
['Language','hard','What figure of speech directly compares without “like” or “as”?',['Metaphor','Simile','Hyperbole','Alliteration'],0,'A metaphor identifies one thing as another for rhetorical effect.'],
['Language','hard','What does “etymology” study?',['Word origins and histories','Sentence punctuation only','Speech volume','Alphabetical sorting'],0,'Etymology tracks how words develop and move between languages.'],
['Gaming','easy','Which game features Creepers?',['Minecraft','Roblox','Fortnite','Among Us'],0,'Creepers are hostile mobs that can explode.'],
['Gaming','easy','In chess, which piece moves in an L shape?',['Knight','Rook','Bishop','Queen'],0,'Knights can jump over pieces.'],
['Gaming','medium','What shape do four blocks form in Tetris?',['Tetromino','Pentomino','Domino','Hexomino'],0,'Seven tetromino shapes are used in standard Tetris play.'],
['Gaming','medium','Which company originally released the Nintendo Switch?',['Nintendo','Sony','Microsoft','Sega'],0,'The Nintendo Switch debuted in 2017.'],
['Gaming','hard','In chess, what does en passant allow?',['A special pawn capture','A king to move twice','A bishop to castle','A rook to promote'],0,'En passant is only available immediately after the relevant two-square pawn advance.'],
['Gaming','hard','What is the maximum number of distinct rotations of a square Tetris O-piece by appearance?',['One','Two','Three','Four'],0,'A square looks unchanged after quarter-turn rotations.'],
["Philippines","superhard","Which Philippine president signed the 1973 Constitution into force?",["Ferdinand Marcos", "Carlos P. Garcia", "Ramon Magsaysay", "Diosdado Macapagal"],0,"The 1973 Constitution was proclaimed ratified during martial law."],
["Philippines","superhard","Which precolonial script has been recognized as one of the traditional Philippine writing systems?",["Baybayin", "Hangul", "Katakana", "Devanagari"],0,"Baybayin was used in parts of the archipelago before Spanish colonization."],
["K-Drama","superhard","Which writer created the Korean television series Signal (2016)?",["Kim Eun-hee", "Park Ji-eun", "Kim Eun-sook", "Noh Hee-kyung"],0,"Kim Eun-hee also wrote the drama Kingdom."],
["K-Drama","superhard","Which historical era provides the primary setting for the drama Mr. Sunshine?",["Late Joseon", "Goryeo founding", "Unified Silla", "Japanese occupation of 1945"],0,"The drama follows characters amid the political turmoil before Japan annexed Korea."],
["History","superhard","Which 1648 treaties are conventionally associated with the end of the Thirty Years’ War?",["Peace of Westphalia", "Treaty of Utrecht", "Treaty of Tordesillas", "Treaty of Paris 1763"],0,"The treaties were negotiated at Münster and Osnabrück."],
["History","superhard","Which empire was ruled by Justinian I in the sixth century?",["Eastern Roman Empire", "Holy Roman Empire", "Ottoman Empire", "Carolingian Empire"],0,"Justinian commissioned the Corpus Juris Civilis."],
["World","superhard","Which international court settles legal disputes between states with their consent?",["International Court of Justice", "International Criminal Court", "European Court of Human Rights", "Permanent Court of Arbitration only"],0,"The ICJ is the principal judicial organ of the United Nations."],
["World","superhard","Which treaty established the European Economic Community?",["Treaty of Rome", "Treaty of Maastricht", "Treaty of Lisbon", "Treaty of Nice"],0,"The EEC was created in 1957."],
["Geography","superhard","Which strait separates the islands of Sumatra and Java?",["Sunda Strait", "Strait of Malacca", "Lombok Strait", "Bering Strait"],0,"Krakatoa is located in the Sunda Strait."],
["Geography","superhard","What is the deepest known oceanic trench?",["Mariana Trench", "Tonga Trench", "Java Trench", "Puerto Rico Trench"],0,"Challenger Deep lies within the Mariana Trench."],
["Science","superhard","Which law relates the entropy of an isolated system to spontaneous processes?",["Second law of thermodynamics", "Boyle’s law", "Ohm’s law", "Kepler’s first law"],0,"The entropy of an isolated system does not decrease in a spontaneous process."],
["Science","superhard","Which organelle contains its own DNA and carries out oxidative phosphorylation?",["Mitochondrion", "Golgi apparatus", "Lysosome", "Peroxisome"],0,"Mitochondria retain a small genome separate from nuclear DNA."],
["Movies","superhard","Who directed the 1954 film Seven Samurai?",["Akira Kurosawa", "Yasujirō Ozu", "Kenji Mizoguchi", "Masaki Kobayashi"],0,"Seven Samurai influenced later ensemble action films."],
["Movies","superhard","Which film won the first Academy Award for Best Animated Feature?",["Shrek", "Spirited Away", "Finding Nemo", "Monsters, Inc."],0,"The category debuted at the 74th Academy Awards."],
["Music","superhard","Which composer wrote the opera The Magic Flute?",["Wolfgang Amadeus Mozart", "Richard Wagner", "Giuseppe Verdi", "Giacomo Puccini"],0,"The Magic Flute premiered in Vienna in 1791."],
["Music","superhard","What is the interval between two pitches separated by six semitones called?",["Tritone", "Perfect fourth", "Major sixth", "Minor third"],0,"The tritone divides the octave into two equal halves."],
["Sports","superhard","In snooker, how many points is the black ball worth?",["Seven", "Six", "Five", "Eight"],0,"Black is the highest-value color ball."],
["Sports","superhard","In Olympic fencing, which weapon has the entire body as a valid target?",["Épée", "Foil", "Sabre", "Rapier"],0,"Épée uses the whole body as its valid target area."],
["Technology","superhard","Which public-key cryptosystem is named after Rivest, Shamir and Adleman?",["RSA", "AES", "SHA-256", "Diffie–Hellman"],0,"RSA was publicly described in 1977."],
["Technology","superhard","Which standard is used for mobile device near-field communication at very short range?",["NFC", "LTE", "DOCSIS", "VDSL"],0,"NFC enables contactless tags and payment taps."],
["Food","superhard","What process gives browned bread crust its characteristic flavor through reactions between sugars and amino compounds?",["Maillard reaction", "Fermentation", "Gelatinization", "Emulsification"],0,"Maillard reactions produce many aroma and flavor compounds."],
["Food","superhard","What is the main protein network formed in wheat dough through kneading?",["Gluten", "Casein", "Albumin", "Collagen"],0,"Glutenin and gliadin proteins contribute to gluten formation."],
["Animals","superhard","Which mammalian order includes whales and dolphins?",["Cetacea", "Sirenia", "Carnivora", "Primates"],0,"Modern taxonomy groups cetaceans within even-toed ungulates."],
["Animals","superhard","Which pigment molecule carries oxygen in many mollusks and arthropods?",["Hemocyanin", "Hemoglobin", "Chlorophyll", "Myoglobin"],0,"Hemocyanin contains copper and can make oxygenated blood appear blue."],
["Space","superhard","Which moon has a dense nitrogen-rich atmosphere and methane lakes?",["Titan", "Europa", "Io", "Ganymede"],0,"Titan is Saturn’s largest moon."],
["Space","superhard","What is the name of the boundary around a black hole beyond which light cannot escape?",["Event horizon", "Accretion disk", "Roche limit", "Heliopause"],0,"The event horizon marks the no-return boundary."],
["Literature","superhard","Who wrote The Master and Margarita?",["Mikhail Bulgakov", "Fyodor Dostoevsky", "Leo Tolstoy", "Anton Chekhov"],0,"The novel was published after Bulgakov’s death."],
["Literature","superhard","Which literary device refers to a narrative that begins in the middle of events?",["In medias res", "Deus ex machina", "Anagnorisis", "Pathetic fallacy"],0,"The Latin phrase means into the midst of things."],
["Art","superhard","Which artist painted The Garden of Earthly Delights?",["Hieronymus Bosch", "Pieter Bruegel the Elder", "Jan van Eyck", "Albrecht Dürer"],0,"The triptych is housed at the Prado Museum in Madrid."],
["Art","superhard","Which art movement is associated with Georges Braque and Pablo Picasso?",["Cubism", "Fauvism", "Rococo", "Dadaism"],0,"Analytic Cubism decomposed subjects into overlapping forms."],
["Mythology","superhard","In Norse mythology, which figure guards the rainbow bridge Bifröst?",["Heimdall", "Tyr", "Baldr", "Freyr"],0,"Heimdall is known as the watchman of the gods."],
["Mythology","superhard","Who is the Greek goddess of the hearth?",["Hestia", "Hera", "Demeter", "Artemis"],0,"Hestia was associated with the home’s sacred fire."],
["Business","superhard","What does the current ratio compare?",["Current assets to current liabilities", "Revenue to total assets", "Debt to equity only", "Operating profit to sales"],0,"The current ratio is a measure of short-term liquidity."],
["Business","superhard","In project management, what is the critical path?",["Longest-duration dependent path", "Shortest list of tasks", "Tasks with highest costs", "Tasks assigned to the sponsor"],0,"A delay on a critical-path activity can delay the overall schedule."],
["Computers","superhard","Which data structure follows first-in, first-out order?",["Queue", "Stack", "Heap", "Tree"],0,"A queue removes items in the same order they arrived."],
["Computers","superhard","Which SQL clause filters groups after aggregation?",["HAVING", "WHERE", "ORDER BY", "LIMIT"],0,"HAVING is evaluated against grouped results."],
["Nature","superhard","Which ecological relationship benefits one organism while harming its host?",["Parasitism", "Mutualism", "Commensalism", "Neutralism"],0,"Parasites exploit a host without usually killing it immediately."],
["Nature","superhard","What is the boundary between the troposphere and stratosphere called?",["Tropopause", "Mesopause", "Stratopause", "Thermocline"],0,"The tropopause height varies with latitude and weather."],
["Language","superhard","What is a morpheme?",["Smallest meaningful language unit", "A sentence stress pattern", "A type of vowel harmony", "A word spelled backward"],0,"A morpheme can be a whole word or a meaningful word part."],
["Language","superhard","Which term describes a language used between speakers of different native languages?",["Lingua franca", "Idiolect", "Isogloss", "Diglossia"],0,"English serves as a lingua franca in many international settings."],
["Gaming","superhard","Which early game designer created the original Tetris in 1984?",["Alexey Pajitnov", "Shigeru Miyamoto", "Hideo Kojima", "John Carmack"],0,"Pajitnov designed Tetris while working in Moscow."],
["Gaming","superhard","In chess notation, which symbol commonly denotes a checkmate?",["#", "+", "!", "?"],0,"A plus sign indicates check, while a hash commonly indicates mate."],
];
export const ART={'Philippines':'🇵🇭','K-Drama':'🎬','History':'🏛️','World':'🌐','Geography':'🗺️','Science':'🔬','Movies':'🍿','Music':'🎵','Sports':'🏅','Technology':'📱','Food':'🍜','Animals':'🦁','Space':'🪐','Literature':'📚','Art':'🎨','Mythology':'⚡','Business':'💼','Computers':'💻','Nature':'🌿','Language':'🔤','Gaming':'🎮'};
export const QUESTIONS=RAW.map((a,i)=>({id:i+1,cat:a[0],diff:a[1],q:a[2],opts:a[3],correct:a[4],trivia:a[5]}));
